# Generated by Django 4.2.3 on 2023-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
